spring.application.name=hitachi-test

# Database Connection
spring.datasource.url=jdbc:h2:mem:hitachi
#spring.datasource.url=jdbc:h2:file:./data/hitachi
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Web Console Interface
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379